# Generated by Django 5.1.1 on 2024-10-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_bebida_adicional_remove_cafete_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='sector',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
