# Generated by Django 5.1.1 on 2024-11-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_mensajecontacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensajeContacto',
        ),
    ]
