from django.urls import path
from  App import views

urlpatterns = [
    path('', views.mostrar_index, name='Principal'),
    path('bebidas/', views.mostrar_bebidas, name='Bebidas'),
    path('comidas/', views.mostrar_comida, name='Comida'),
    path('pedidos/', views.mostrar_pedidos, name='Pedido'),
    path('pedidos_cliente/', views.mostrar_pedidos_cliente, name='Mostrar Pedidos Cliente'),
    path('categorias/', views.mostrar_categoria, name='Categoria'),
    path('guarniciones/', views.mostrar_guarnicion, name='Guarnicion'),
    path('CafeTe/', views.mostrar_cafe_te, name='CafeTe'),
    path('adicionales/', views.mostrar_adicional, name='Adicional'),
    path('mesas/', views.mostrar_mesas, name='Mesa'),
    path('postres/', views.mostrar_postres, name='Postre'),
    path('crear_bebidas/', views.crear_bebida, name='Crear Bebida'),
    path('crear_comida/',  views.crear_comida, name='Crear Comida'),
    path('crear_categoria/', views.crear_categoria, name='Crear Categoria'),
    path('crear_adicional/', views.crear_adicional, name='Crear Adicional'),
    path('crear_guarnicion/', views.crear_guarnicion, name='Crear Guarnicion'),
    path('crear_postre/', views.crear_postre, name='Crear Postre'),
    path('crear_cafete/', views.crear_cafete, name='Crear CafeTe'),
    path('crear_mesa/', views.crear_mesa, name='Crear Mesa'),
    path('crear_pedido/', views.crear_pedido, name='Crear Pedido'),
    path('crear_pedido_cliente/', views.crear_pedido_cliente, name='Crear Pedido Cliente'),
    path('buscar_comida/', views.buscar_comida, name='Buscar Comida'),
    path('buscar_adicional/', views.buscar_adicional, name='Buscar Adicional'),
    path('buscar_guarnicion/', views.buscar_guarnicion, name='Buscar Guarnicion'),
    path('buscar_cafete/', views.buscar_cafete, name='Buscar CafeTe'),
    path('buscar_bebida/', views.buscar_bebida, name='Buscar Bebida'),
    path('buscar_mesa/', views.buscar_mesa, name='Buscar Mesa'),
    path('buscar_categoria/', views.buscar_categoria, name='Buscar Categoria'),
    path('buscar_postre/', views.buscar_postre, name='Buscar Postre'),
    path('buscar_pedido/', views.buscar_pedido, name='Buscar Pedido'),
    path('actualizar_comida/<comida_id>/', views.actualizar_comida, name='Actualizar Comida'),
    path('actualizar_bebida/<bebida_id>/', views.actualizar_bebida, name='Actualizar Bebida'),
    path('actualizar_categoria/<categoria_id>/', views.actualizar_categoria, name='Actualizar Categoria'),
    path('actualizar_guarnicion/<guarnicion_id>/', views.actualizar_guarnicion, name='Actualizar Guarnicion'),
    path('actualizar_cafete/<cafete_id>/', views.actualizar_cafete, name='Actualizar CafeTe'),
    path('actualizar_postre/<postre_id>/', views.actualizar_postre, name='Actualizar Postre'),
    path('actualizar_adicional/<adicional_id>/', views.actualizar_adicional, name='Actualizar Adicional'),
    path('actualizar_pedido/<pedido_id>/', views.actualizar_pedido, name='Actualizar Pedido'),
    path('actualizar_mesa/<int:id>/', views.actualizar_mesa, name='Actualizar Mesa'),
    path('eliminar_mesa/<mesa_id>/', views.eliminar_mesa, name='Eliminar Mesa'),
    path('eliminar_comida/<comida_id>/', views.eliminar_comida, name='Eliminar Comida'),
    path('eliminar_bebida/<bebida_id>/', views.eliminar_bebida, name='Eliminar Bebida'),
    path('eliminar_categoria/<categoria_id>/', views.eliminar_categoria, name='Eliminar Categoria'),
    path('eliminar_pedido/<pedido_id>/', views.eliminar_pedido, name='Eliminar Pedido'),
    path('eliminar_guarnicion/<guarnicion_id>/', views.eliminar_guarnicion, name='Eliminar Guarnicion'),
    path('eliminar_adicional/<int:adicional_id>/', views.eliminar_adicional, name='Eliminar Adicional'),
    path('eliminar_cafete/<cafete_id>/', views.eliminar_cafete, name='Eliminar CafeTe'),
    path('eliminar_postre/<postre_id>/', views.eliminar_postre, name='Eliminar Postre'),
    path('registro/', views.registro_usuario,name='Registro'),
    path('login/', views.login_request, name= 'login'),
    path('logout/', views.logout_request,name='logout'),
    path('politica_privacidad/', views.politica_privacidad, name='Politica Privacidad'),
    path('terminos_condiciones/', views.terminos_condiciones, name='Terminos Condiciones'),
    path('contacto/',views.contacto,name='Contacto'),
    path('gracias/',views.pagina_de_gracias,name='pagina_de_gracias'),
    path('mensajes/', views.listar_mensajes,name='Listar Mensajes'),
    path('about/', views.mostrar_about, name='About'),


]